let
  grey = "242";
  red = "1";
  yellow = "3";
  blue = "4";
  magenta = "5";
  cyan = "6";
  white = "7";
in
{
  POWERLEVEL9K_DISABLE_HOT_RELOAD = true;
  POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD = true;
  POWERLEVEL9K_PROMPT_ADD_NEWLINE = false;
  POWERLEVEL9K_INSTANT_PROMPT = "off";
  POWERLEVEL9K_TRANSIENT_PROMPT = "off";

  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS = [
    "context" # user@host
    "dir" # current directory
    "vcs" # git status
    "command_execution_time" # previous command duration
    "newline" # \n
    "virtualenv" # python virtual environment
    "prompt_char" # prompt symbol
  ];

  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS = [
    "newline"
  ];

  POWERLEVEL9K_BACKGROUND = ""; # transparent background
  POWERLEVEL9K_LEFT_LEFT_WHITESPACE = "";
  POWERLEVEL9K_LEFT_RIGHT_WHITESPACE = "";
  POWERLEVEL9K_RIGHT_LEFT_WHITESPACE = "";
  POWERLEVEL9K_RIGHT_RIGHT_WHITESPACE = "";
  POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR = " ";
  POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR = " ";
  POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR = "";
  POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR = "";
  POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION = "";

  POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND = magenta;
  POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND = magenta;
  POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND = magenta;
  POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND = red;
  POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND = red;
  POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND = red;
  POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION = "❯";
  POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION = "❯";
  POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION = "❮";
  POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION = "❮";
  POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_CONTENT_EXPANSION = "❮";
  POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_CONTENT_EXPANSION = "❮";
  POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE = false;

  POWERLEVEL9K_VIRTUALENV_FOREGROUND = grey;
  POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION = false;
  POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER = "";
  POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER = "";
  POWERLEVEL9K_DIR_FOREGROUND = blue;

  POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE = "%F{$white}%n%f%F{$grey}@%m%f";
  POWERLEVEL9K_CONTEXT_TEMPLATE = "%F{$grey}%n@%m%f";
  POWERLEVEL9K_CONTEXT_DEFAULT_CONTENT_EXPANSION = "";
  POWERLEVEL9K_CONTEXT_SUDO_CONTENT_EXPANSION = "";

  POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD = 3;
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION = 1;
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT = "d h m s";
  POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND = yellow;

  POWERLEVEL9K_VCS_FOREGROUND = grey;
  POWERLEVEL9K_VCS_LOADING_TEXT = "";
  POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS = 0;

  # Cyan ahead/behind arrows.
  POWERLEVEL9K_VCS_INCOMING_CHANGESFORMAT_FOREGROUND = cyan;
  POWERLEVEL9K_VCS_OUTGOING_CHANGESFORMAT_FOREGROUND = cyan;
  POWERLEVEL9K_VCS_GIT_HOOKS = [ "vcs-detect-changes" "git-untracked" "git-aheadbehind" ];
  POWERLEVEL9K_VCS_BRANCH_ICON = "";
  POWERLEVEL9K_VCS_COMMIT_ICON = "@";
  POWERLEVEL9K_VCS_STAGED_ICON = "";
  POWERLEVEL9K_VCS_UNSTAGED_ICON = "";
  POWERLEVEL9K_VCS_UNTRACKED_ICON = "";

  POWERLEVEL9K_VCS_DIRTY_ICON = "*";
  POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON = ":⇣";
  POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON = ":⇡";
  POWERLEVEL9K_VCS_COMMITS_AHEAD_MAX_NUM = 1;
  POWERLEVEL9K_VCS_COMMITS_BEHIND_MAX_NUM = 1;
  POWERLEVEL9K_VCS_CONTENT_EXPANSION = "\${\${\${P9K_CONTENT/⇣* :⇡/⇣⇡}// }//:/ }";

  POWERLEVEL9K_TIME_FOREGROUND = grey;
  POWERLEVEL9K_TIME_FORMAT = "%D{%H:%M:%S}";
  POWERLEVEL9K_TIME_UPDATE_ON_COMMAND = false;
}
